CROSSCOMPILE?=/opt1/cleanSDK/codesourcery/arm-2013.05/bin/arm-none-linux-gnueabi-
CC= $(CROSSCOMPILE)gcc
OBJCOPY= $(CROSSCOMPILE)objcopy
OBJDUMP= $(CROSSCOMPILE)objdump

joyevents:joyevents.c
	$(CC) $(CFLAGS) -o joyevents joyevents.c

