all:
	$(CC) $(CFLAGS) -O2 -o i2c_write i2c_write.c
	$(CC) $(CFLAGS) -O2 -o i2c_check i2c_check.c
	$(CC) $(CFLAGS) -O2 -o edid_write edid_write.c

clean:
	rm -f i2c_write
	rm -f i2c_check
	rm -f edid_write